FROM node:12.11.1-alpine

ENV DB_HOST DB_HOST
ENV DB_NAME DB_NAME
ENV DB_PORT DB_PORT
ENV DB_USER DB_USER
ENV DB_PASSWORD DB_PASSWORD
ENV BOT_LANG ru
ENV PANEL_PASSWORD PANEL_PASSWORD
ENV PANEL_PORT PANEL_PORT
ENV PANEL_USERNAME PANEL_USERNAME
ENV TWITCH_BOTUSERNAME TWITCH_BOTUSERNAME
ENV TWITCH_BROADCASTERTOKEN TWITCH_BROADCASTERTOKEN
ENV TWITCH_CHANNEL TWITCH_CHANNEL
ENV TWITCH_CLIENTID gzq39cbxvky7fiux0tb74ho7ekms8d
ENV TWITCH_TOKEN TWITCH_TOKEN
ENV TZ Europe/Moscow
RUN apk add --no-cache bash

EXPOSE 3000

COPY . /app
WORKDIR /app

RUN npm i
RUN npm run build

CMD npm start