name: Publish Docker GitLab

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-docker]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Docker Build & Push to Gitlab
        uses: opspresso/action-docker@v0.2.8
        env:
          USERNAME: ${{ secrets.GITLAB_DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.GITLAB_DOCKER_PASSWORD }}
          REGISTRY: registry.gitlab.com
          IMAGE_NAME: 'satont/yakui'
          TAG_NAME: ${{ github.sha }}
          LATEST: 'true'
